spring:
  application:
    name: backend-quiz-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quiz_system
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
