version: '3.8'

services:
  quiz-system-db:
    image: postgres
    container_name: quiz-system-db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command: postgres -p 5432
    ports:
      - "5432:5432"